### ISSUE TITLE
Encoding Issues with capital Umlauts

### ISSUE THREAD

**Issue by gruselglatz** [rclement/business-card-generator#173]
Create a VCard with capital letter umlauts and you get strange Symbols when you scan it with an iPhone.

**Comment by rclement** [comment]
Hi @gruselglatz , thanks for submitting this issue.

I tried to reproduce the issue using for instance "Über" as first name and iOS 15 recognizes perfectly the UTF-8 symbol:
https://business-card-generator.vercel.app/card?card_type=vcard&firstname=%C3%9Cber&lastname=Joe&nickname=&picture=&birthday=&company=&job=&email=&phone=&website=&street=&city=&zipcode=&state=&country=

Could you provide a reproducible link please? (generate a problematic VCard and share the URL here)

**Comment by gruselglatz** [comment]
Hi,

yeah sry:
https://business-card-generator.vercel.app/card?card_type=vcard&firstname=%C3%96%C3%96%C3%96&lastname=%C3%9C%C3%9C%C3%9C&nickname=&picture=&birthday=&company=&job=&email=&phone=&website=&street=&city=&zipcode=&state=&country=

![image](https://github.com/rclement/business-card-generator/assets/15243394/81c61406-4cae-4961-af00-50c24e547a6c)

**Comment by rclement** [comment]
Issue should be fixed with PR #174.

@gruselglatz could you confirm the fix with the preview deployment before I merge into `main` please?
https://qr-unicode-bcardgen.vercel.app/card?card_type=vcard&firstname=%C3%96%C3%96%C3%96&lastname=%C3%9C%C3%9C%C3%9C&nickname=&picture=&birthday=&company=&job=&email=&phone=&website=&street=&city=&zipcode=&state=&country=

**Comment by gruselglatz** [comment]
LGTM, thanks for the superfast response 👍 👍

**Comment by rclement** [comment]
Fixed is shipped and deployed as part of version 0.3.0. Thanks for reporting!
